name = "line-crm-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true

# API_KEY is set via `wrangler secret put API_KEY`
# Do NOT hardcode secrets here

[vars]
WORKER_URL = "https://line-rm-worker.line-crm-api.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "line-crm"
database_id = "54054562-ae22-4512-8d81-9152f8056299"

[triggers]
crons = ["*/5 * * * *"]
